#!/bin/sh

. /Applications/bitnami-wordpress/scripts/setenv.sh
SASL_PATH="/Applications/bitnami-wordpress/common/lib/sasl2"
                export SASL_PATH
exec /Applications/bitnami-wordpress/common/sbin/.saslpasswd2.bin -f "/Applications/bitnami-wordpress/common/etc/sasldb2" "$@"
